version: "3.7"

services:
  php-apache:
    image: php:8.2-apache
    ports:
      - "8081:80"
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shop
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_pass
    volumes:
      - db_data:/var/lib/mysql

  openssh-server:
    image: linuxserver/openssh-server:version-9.6_p1-r0
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD_ACCESS=true 
      - USER_PASSWORD=Mpass
      - USER_NAME=Muser
      - LOG_STDOUT= #optional
    ports:
      - 2222:2222
    restart: unless-stopped

volumes:
  db_data:
