version: "3.7"

services:
  php-apache:
    image: php:8.2-apache
    ports:
      - "8081:80"
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shop
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
